name: apps_blog
version: "1.0"
config-version: 2

models:
  apps_blog:                # MUST match models/apps_blog/
    +database: staging      # keep DB consistent
    +schema: analytics

    raw:
      +schema: stage
      materialized: table

    stage:
      +schema: post_stage
      materialized: view

    core:
      +schema: core
      materialized: table
